export let Get_Music_Records_Request="Get_Music_Records_Request"
export let Get_Music_Records_success="Get_Music_Records_Success"
export let Get_Music_Records_Failure="Get_Music_Records_Failure"

export let Get_filter_data="Get_filter_data"

export let Edit_Music_Records_Request="Edit_Music_Records_Request"
export let Edit_Music_Records_success="Edit_Music_Records_Success"
export let Edit_Music_Records_Failure="Edit_Music_Records_Failure"